package com.lxhdj.dao.model;

import java.util.Date;

public class Mission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.name
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.business_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mission_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Long missionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mission_type_l2
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Long missionTypeL2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.start_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.end_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.finish_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.status
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.create_mis_code
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private String createMisCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.ctime
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.update_mis_code
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private String updateMisCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.utime
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.remark
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.sort_order
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.create_mis_name
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private String createMisName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mission_object_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer missionObjectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.collection_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer collectionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.quota_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer quotaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.tags
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.priority
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mission_monitor_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer missionMonitorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.predict_process_rate
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer predictProcessRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.show_finish_view_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer showFinishViewType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.bd_transfer
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer bdTransfer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.plan_id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Long planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.min_process_threshold
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer minProcessThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.strategy_id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Long strategyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.min_quota_threshold
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    private Integer minQuotaThreshold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.id
     *
     * @return the value of mission.id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.id
     *
     * @param id the value for mission.id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.name
     *
     * @return the value of mission.name
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.name
     *
     * @param name the value for mission.name
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.business_type
     *
     * @return the value of mission.business_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.business_type
     *
     * @param businessType the value for mission.business_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mission_type
     *
     * @return the value of mission.mission_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Long getMissionType() {
        return missionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mission_type
     *
     * @param missionType the value for mission.mission_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setMissionType(Long missionType) {
        this.missionType = missionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mission_type_l2
     *
     * @return the value of mission.mission_type_l2
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Long getMissionTypeL2() {
        return missionTypeL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mission_type_l2
     *
     * @param missionTypeL2 the value for mission.mission_type_l2
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setMissionTypeL2(Long missionTypeL2) {
        this.missionTypeL2 = missionTypeL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.start_time
     *
     * @return the value of mission.start_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.start_time
     *
     * @param startTime the value for mission.start_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.end_time
     *
     * @return the value of mission.end_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.end_time
     *
     * @param endTime the value for mission.end_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.finish_time
     *
     * @return the value of mission.finish_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.finish_time
     *
     * @param finishTime the value for mission.finish_time
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.status
     *
     * @return the value of mission.status
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.status
     *
     * @param status the value for mission.status
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.create_mis_code
     *
     * @return the value of mission.create_mis_code
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public String getCreateMisCode() {
        return createMisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.create_mis_code
     *
     * @param createMisCode the value for mission.create_mis_code
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setCreateMisCode(String createMisCode) {
        this.createMisCode = createMisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.ctime
     *
     * @return the value of mission.ctime
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.ctime
     *
     * @param ctime the value for mission.ctime
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.update_mis_code
     *
     * @return the value of mission.update_mis_code
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public String getUpdateMisCode() {
        return updateMisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.update_mis_code
     *
     * @param updateMisCode the value for mission.update_mis_code
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setUpdateMisCode(String updateMisCode) {
        this.updateMisCode = updateMisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.utime
     *
     * @return the value of mission.utime
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.utime
     *
     * @param utime the value for mission.utime
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.remark
     *
     * @return the value of mission.remark
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.remark
     *
     * @param remark the value for mission.remark
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.sort_order
     *
     * @return the value of mission.sort_order
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.sort_order
     *
     * @param sortOrder the value for mission.sort_order
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.create_mis_name
     *
     * @return the value of mission.create_mis_name
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public String getCreateMisName() {
        return createMisName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.create_mis_name
     *
     * @param createMisName the value for mission.create_mis_name
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setCreateMisName(String createMisName) {
        this.createMisName = createMisName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mission_object_type
     *
     * @return the value of mission.mission_object_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getMissionObjectType() {
        return missionObjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mission_object_type
     *
     * @param missionObjectType the value for mission.mission_object_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setMissionObjectType(Integer missionObjectType) {
        this.missionObjectType = missionObjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.collection_type
     *
     * @return the value of mission.collection_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getCollectionType() {
        return collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.collection_type
     *
     * @param collectionType the value for mission.collection_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setCollectionType(Integer collectionType) {
        this.collectionType = collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.quota_type
     *
     * @return the value of mission.quota_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getQuotaType() {
        return quotaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.quota_type
     *
     * @param quotaType the value for mission.quota_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setQuotaType(Integer quotaType) {
        this.quotaType = quotaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.tags
     *
     * @return the value of mission.tags
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.tags
     *
     * @param tags the value for mission.tags
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.priority
     *
     * @return the value of mission.priority
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.priority
     *
     * @param priority the value for mission.priority
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mission_monitor_type
     *
     * @return the value of mission.mission_monitor_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getMissionMonitorType() {
        return missionMonitorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mission_monitor_type
     *
     * @param missionMonitorType the value for mission.mission_monitor_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setMissionMonitorType(Integer missionMonitorType) {
        this.missionMonitorType = missionMonitorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.predict_process_rate
     *
     * @return the value of mission.predict_process_rate
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getPredictProcessRate() {
        return predictProcessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.predict_process_rate
     *
     * @param predictProcessRate the value for mission.predict_process_rate
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setPredictProcessRate(Integer predictProcessRate) {
        this.predictProcessRate = predictProcessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.show_finish_view_type
     *
     * @return the value of mission.show_finish_view_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getShowFinishViewType() {
        return showFinishViewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.show_finish_view_type
     *
     * @param showFinishViewType the value for mission.show_finish_view_type
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setShowFinishViewType(Integer showFinishViewType) {
        this.showFinishViewType = showFinishViewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.bd_transfer
     *
     * @return the value of mission.bd_transfer
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getBdTransfer() {
        return bdTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.bd_transfer
     *
     * @param bdTransfer the value for mission.bd_transfer
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setBdTransfer(Integer bdTransfer) {
        this.bdTransfer = bdTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.plan_id
     *
     * @return the value of mission.plan_id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.plan_id
     *
     * @param planId the value for mission.plan_id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.min_process_threshold
     *
     * @return the value of mission.min_process_threshold
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getMinProcessThreshold() {
        return minProcessThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.min_process_threshold
     *
     * @param minProcessThreshold the value for mission.min_process_threshold
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setMinProcessThreshold(Integer minProcessThreshold) {
        this.minProcessThreshold = minProcessThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.strategy_id
     *
     * @return the value of mission.strategy_id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Long getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.strategy_id
     *
     * @param strategyId the value for mission.strategy_id
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setStrategyId(Long strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.min_quota_threshold
     *
     * @return the value of mission.min_quota_threshold
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public Integer getMinQuotaThreshold() {
        return minQuotaThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.min_quota_threshold
     *
     * @param minQuotaThreshold the value for mission.min_quota_threshold
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    public void setMinQuotaThreshold(Integer minQuotaThreshold) {
        this.minQuotaThreshold = minQuotaThreshold;
    }
}