package com.lxhdj.dao.mapper;

import com.lxhdj.dao.model.Mission;
import com.lxhdj.dao.model.MissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    long countByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    int deleteByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    int insert(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    int insertSelective(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    List<Mission> selectByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    Mission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    int updateByExampleSelective(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    int updateByExample(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    int updateByPrimaryKeySelective(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Thu Apr 14 21:21:14 CST 2022
     */
    int updateByPrimaryKey(Mission record);

    void selectByPrimaryKey();
}